apiVersion: v1
kind: Pod
metadata:
  name: with-node-anti-affinity-required
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: NotIn
            values:
            - expense
  containers:
  - name: with-node-anti-affinity
    image: nginx

# Important Point on Node Anti-Affinity:
# Kubernetes doesn't have a nodeAntiAffinity field because all node selection is handled through nodeAffinity. Anti-affinity behavior is expressed using negative operators like NotIn or DoesNotExist within nodeAffinity.

# Label the node:
# Quick checklist for this to work:
# Label your node:
# kubectl label node ip-192-168-14-127.ec2.internal project=expense

# Create the pod with your YAML file:
# kubectl apply -f 04-node-anti-affinity-required.yaml

# Check pod placement and node labels:
# kubectl get pods -o wide
# kubectl get nodes --show-labels
